replicaCount: 2
image:
  repository: accountingbots/ai-agent
  tag: latest
service:
  type: ClusterIP
  port: 8080
resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"
